[repo]
name = "terminility"
category = "util-repos"
kind = "shell"

[paths]
disk_path = "."
profile_path = ".tachometer/profile.json"
summary_path = ".tachometer/summary.json"

[defaults]
label = "repo-snapshot"
